use_frameworks!

platform :ios, '8.0'

target 'CYPodLib_Example' do
  pod 'CYPodLib', :path => '../'

  target 'CYPodLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
